name: Java CI

on:
  push:
    branches: [ master, dev, release/* ]
  pull_request:
    branches: [ master, dev, release/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 9
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 9
      - name: Build with Maven
        run: mvn -B package --file pom.xml
